# Identificación y Puerto
spring.application.name=labo
server.port=8081

# --- CONFIGURACIÓN ORACLE LOCAL (XE) ---
# Conexión directa a tu PC (localhost) al puerto 1521 y al servicio 'xe'
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=C##MAESTRO
spring.datasource.password=Duoc1234$$3210
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# --- JPA / HIBERNATE ---
# 'update' es clave: Spring creará las tablas automáticamente en tu base local
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# --- LOGS ---
logging.level.root=INFO
logging.level.com.laboratorio.labo=DEBUG