spring.application.name=labo
server.port=8081

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=C##MAESTRO
spring.datasource.password=Duoc1234$$3210
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

logging.level.root=INFO
logging.level.com.laboratorio.labo=DEBUG